### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Shigino** [rustysec/win-event-log-rs#1]
Hello,

This crate looks really cool, I need something like it for a small project I'm working on. But win-event-log-rs currently has no LICENSE, which prevents me from using or contributing to the crate! (I'm planning on implementing callback-based subscribes).

Could you consider adding a license to the project? The [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) provides information about how to apply a license to a Rust project. I recommend using the MIT/Apache-2 License, as to be maximally compatible with the rest of the Rust ecosystem.

Thanks

**Comment by xwang-r7** [comment]
@rustysec I would also like to contribute to this repo by add a filter for timestamp. but looks like a license is needed.

**Comment by rustysec** [comment]
Apologies this took me so long to respond to, I added a license to the repo.
